apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ratings-test-abort
  namespace: samplenode
spec:
  destination:
    name: reviews
  httpFault:
    abort:
      httpStatus: 500
      percent: 100
  precedence: 2
  route:
  - labels:
      version: v1