apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2018-05-10T20:07:23Z'
  generation: 8
  labels:
    app: mongodb
  name: mongodb
  namespace: samplenode
  resourceVersion: '916789'
  selfLink: /apis/apps.openshift.io/v1/namespaces/samplenode/deploymentconfigs/mongodb
  uid: c0afce1b-548d-11e8-928d-001a4a1602c4
spec:
  replicas: 1
  selector:
    app: mongodb
    deploymentconfig: mongodb
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: mongodb
        deploymentconfig: mongodb
    spec:
      containers:
        - env:
            - name: MONGODB_DATABASE
              value: test
            - name: MONGODB_USER
              value: user
            - name: MONGODB_PASSWORD
              value: pass
            - name: MONGODB_ADMIN_PASSWORD
              value: admin_pass
          image: >-
            registry.access.redhat.com/rhscl/mongodb-32-rhel7@sha256:4ed8eb86e5ab93e8c74ce86fbfff4f06e6d9474c28c05ddeefa48464f579abf2
          imagePullPolicy: Always
          name: mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mongodb/data
              name: mongodb-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: mongodb-1
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - mongodb
        from:
          kind: ImageStreamTag
          name: 'mongodb:latest'
          namespace: openshift
        lastTriggeredImage: >-
          registry.access.redhat.com/rhscl/mongodb-32-rhel7@sha256:4ed8eb86e5ab93e8c74ce86fbfff4f06e6d9474c28c05ddeefa48464f579abf2
      type: ImageChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2018-05-10T20:16:17Z'
      lastUpdateTime: '2018-05-10T20:16:17Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
    - lastTransitionTime: '2018-05-10T20:16:18Z'
      lastUpdateTime: '2018-05-10T20:16:19Z'
      message: replication controller "mongodb-7" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 7
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
