apiVersion: v1
kind: Secret
metadata:
  name: mongodb-login
type: Opaque
data:
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2018-05-14T17:55:59Z'
  generation: 2
  labels:
    app: mongodb-36-rhel7
  name: mongodb-36-rhel7
  resourceVersion: '1620163'
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/samplenode/deploymentconfigs/mongodb-36-rhel7
  uid: 0ee31bdf-57a0-11e8-928d-001a4a1602c4
spec:
  replicas: 1
  selector:
    app: mongodb-36-rhel7
    deploymentconfig: mongodb-36-rhel7
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: mongodb-36-rhel7
        deploymentconfig: mongodb-36-rhel7
    spec:
      containers:
        - env:
            - name: MONGODB_ADMIN_PASSWORD
              value: admin_pass
          image: >-
            registry.access.redhat.com/rhscl/mongodb-36-rhel7
          imagePullPolicy: Always
          name: mongodb-36-rhel7
          ports:
            - containerPort: 27017
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mongodb/data
              name: mongodb-36-rhel7-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: mongodb-36-rhel7-1
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - mongodb-36-rhel7
        from:
          kind: ImageStreamTag
          name: 'mongodb-36-rhel7:latest'
      type: ImageChange
status:
  availableReplicas: 0
  conditions:
    - lastTransitionTime: '2018-05-14T17:55:59Z'
      lastUpdateTime: '2018-05-14T17:55:59Z'
      message: Deployment config does not have minimum availability.
      status: 'False'
      type: Available
    - lastTransitionTime: '2018-05-14T17:56:01Z'
      lastUpdateTime: '2018-05-14T17:56:01Z'
      message: >-
        replication controller "mongodb-36-rhel7-1" is waiting for pod
        "mongodb-36-rhel7-1-deploy" to run
      status: Unknown
      type: Progressing
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 1
  observedGeneration: 2
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    deploymentconfig: mongodb-36-rhel7
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}