apiVersion: v1
kind: Service
metadata:
   name: mongo
   labels:
     run: mongo
spec:
  ports:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27107
  selector:
    run: mongo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: mongo
spec:
   template:
     metadata:
       labels:
         run: mongo
     spec:
       containers:
       - name: mongo
         image: mongo
         ports:
         - containerPort: 27017