kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "mongo4"
spec:
  template: 
    metadata:
      labels:
        name: "mongo4"
    spec:
      containers:
        - name: "mongo4"
          image: "openshift/mongodb:latest"
          ports:
            - containerPort: 27017
              protocol: "TCP"
  replicas: 1
  selector:
    name: "mongo4"
  triggers:
    - type: "ConfigChange" 
  strategy: 
    type: "Rolling"
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo4
spec:
  replicas: 1  
  selector:    
    name: mongo4
  template:    
    metadata:
      labels:  
        name: mongo4 
    spec:
      containers:
      - image: openshift/mongodb:latest
        name: mongo4
        ports:
        - containerPort: 27017
          protocol: TCP
      restartPolicy: Always