apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalog
  name: catalog
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: catalog
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: catalog
spec:
  template: 
    metadata:
      labels:
        name: catalog
    spec:
      containers:
        - name: catalog
          env:
            - name: MONGO_CONNECTION_STRING
              value: 'mongodb://admin:admin_pass@mongodb'
            - name: MONGO_DBNAME
              value: test
          image: docker.io/deewhyweb/node-service:latest
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              protocol: "TCP"
  replicas: 1 
  selector:
    name: "catalog"
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "catalog"
        from:
          kind: "ImageStreamTag"
          name: "node-service:latest"
  strategy: 
    type: "Rolling"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nodeservice
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: catalog
          servicePort: 8080
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: catalog
  name: catalog
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: catalog
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
      routerName: router
      wildcardPolicy: None
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gwservice
  name: gwservice
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: gw
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: gw
spec:
  template: 
    metadata:
      labels:
        name: gw
    spec:
      containers:
        - name: gw
          image: docker.io/deewhyweb/gw:latest
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              protocol: "TCP"
  replicas: 1 
  selector:
    name: "gw"
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "gw"
        from:
          kind: "ImageStreamTag"
          name: "gw:latest"
  strategy: 
    type: "Rolling"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gwservice
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: gwervice
          servicePort: 8080
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: gwservice
  name: gwservice
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: gwservice
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
      routerName: router
      wildcardPolicy: None

      
      