apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configuration
data:
  connection_string: 'mongodb://admin:admin_pass@mongodb.samplenode.svc:27017'
  db_name: test
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalog
  name: catalog
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: catalog
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: catalog
spec:
  template: 
    metadata:
      labels:
        name: catalog
        app: catalog
    spec:
      containers:
        - name: catalog
          env:
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: mongo-configuration
                  key: connection_string
            - name: MONGO_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-configuration
                  key: db_name
          image: docker.io/deewhyweb/node-service:latest
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              protocol: "TCP"
          resources:
              requests:
                cpu: 100m 
                memory: 200Mi 
              limits:
                cpu: 200m 
                memory: 400Mi 
  replicas: 1 
  selector:
    name: "catalog"
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "catalog"
        from:
          kind: "ImageStreamTag"
          name: "node-service:latest"
  strategy: 
    type: "Rolling"
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: catalog
  name: catalog
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: catalog
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
      routerName: router
      wildcardPolicy: None
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gwservice
  name: gwservice
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: gw
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: gw
spec:
  template: 
    metadata:
      labels:
        name: gw
        app: gateway
    spec:
      containers:
        - name: gw
          image: docker.io/deewhyweb/gw:latest
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              protocol: "TCP"
          resources:
              requests:
                cpu: 100m 
                memory: 200Mi 
              limits:
                cpu: 200m 
                memory: 400Mi
  replicas: 1 
  selector:
    name: "gw"
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "gw"
        from:
          kind: "ImageStreamTag"
          name: "gw:latest"
  strategy: 
    type: "Rolling"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gwservice
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: gwervice
          servicePort: 8080
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: gwservice
  name: gwservice
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: gwservice
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
      routerName: router
      wildcardPolicy: None
---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: reviews
spec:
  template: 
    metadata:
      labels:
        name: reviews
        app: reviews
    spec:
      containers:
        - name: reviews
          env:
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: mongo-configuration
                  key: connection_string
            - name: MONGO_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-configuration
                  key: db_name
          image: reviews:latest
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              protocol: "TCP"
          resources:
              requests:
                cpu: 100m 
                memory: 200Mi 
              limits:
                cpu: 200m 
                memory: 400Mi
  replicas: 1 
  selector:
    name: "reviews"
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "reviews"
        from:
          kind: "ImageStreamTag"
          name: "reviews:latest"
  strategy: 
    type: "Rolling"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reviews
  name: reviews
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: reviews
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {} 
---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: cart
spec:
  template: 
    metadata:
      labels:
        name: cart
        app: cart
    spec:
      containers:
        - name: cart
          env:
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: mongo-configuration
                  key: connection_string
            - name: MONGO_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-configuration
                  key: db_name
          image: cart:latest
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              protocol: "TCP"
          resources:
              requests:
                cpu: 100m 
                memory: 200Mi 
              limits:
                cpu: 200m 
                memory: 400Mi
  replicas: 1 
  selector:
    name: "cart"
  triggers:
    - type: "ConfigChange" 
    - type: "ImageChange" 
      imageChangeParams:
        automatic: true
        containerNames:
          - "cart"
        from:
          kind: "ImageStreamTag"
          name: "cart:latest"
  strategy: 
    type: "Rolling"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cart
  name: cart
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: cart
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}   

      
      