apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: gateway
      namespace: samplenode
      labels:
        project: gateway
        version: 1.0.0
        provider: nodeshift
        app: gateway
      annotations:
        nodeshift/git-branch: master
        nodeshift/git-commit: 1184ef60b458218af02aa2609902dc32b91db29a
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        app: gateway
        project: gateway
        provider: nodeshift
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - gateway
            from:
              kind: ImageStreamTag
              name: 'gateway:latest'
      template:
        metadata:
          labels:
            project: gateway
            version: 1.0.0
            provider: nodeshift
            app: gateway
            name: gateway
          annotations:
            sidecar.istio.io/inject: 'true'
            nodeshift/git-branch: master
            nodeshift/git-commit: 1184ef60b458218af02aa2609902dc32b91db29a
        spec:
          containers:
            - readinessProbe:
                httpGet:
                  path: /api/health/readiness
                  scheme: HTTP
                  port: 3000
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 5
                successThreshold: 1
                timeoutSeconds: 1
              livenessProbe:
                httpGet:
                  path: /api/health/liveness
                  scheme: HTTP
                  port: 3000
                initialDelaySeconds: 60
                periodSeconds: 3
                failureThreshold: 2
                successThreshold: 1
                timeoutSeconds: 1
              image: gateway
              name: gateway
              securityContext:
                privileged: false
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              env:
                - name: MONGO_CONNECTION_STRING
                  valueFrom:
                    configMapKeyRef:
                      key: connection_string
                      name: mongo-configuration
                - name: MONGO_DBNAME
                  valueFrom:
                    configMapKeyRef:
                      key: db_name
                      name: mongo-configuration
              resources: null
              limits:
                cpu: 200m
                memory: 400Mi
              requests:
                cpu: 100m
                memory: 200Mi
  - apiVersion: v1
    kind: Route
    spec:
      to:
        kind: Service
        name: gateway
      port:
        targetPort: 8080
    metadata:
      name: gateway
      namespace: samplenode
      labels:
        project: gateway
        version: 1.0.0
        provider: nodeshift
  - apiVersion: v1
    kind: Service
    spec:
      selector:
        project: gateway
        provider: nodeshift
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          name: http
      type: ClusterIP
    metadata:
      name: gateway
      namespace: samplenode
      labels:
        project: gateway
        version: 1.0.0
        provider: nodeshift
      annotations:
        nodeshift/git-branch: master
        nodeshift/git-commit: 1184ef60b458218af02aa2609902dc32b91db29a
