apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ravenclaw
      namespace: demojam
      labels:
        project: ravenclaw
        version: 1.0.0
        provider: nodeshift
        app: ravenclaw
      annotations:
        nodeshift/git-branch: demojam
        nodeshift/git-commit: df797099435c086139688785420555b4a576770b
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        app: ravenclaw
        project: ravenclaw
        provider: nodeshift
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ravenclaw
            from:
              kind: ImageStreamTag
              name: 'ravenclaw:latest'
      template:
        metadata:
          labels:
            project: ravenclaw
            version: 1.0.0
            provider: nodeshift
            app: ravenclaw
            name: ravenclaw
          annotations:
            sidecar.istio.io/inject: 'true'
            nodeshift/git-branch: demojam
            nodeshift/git-commit: df797099435c086139688785420555b4a576770b
        spec:
          containers:
            - readinessProbe:
                httpGet:
                  path: /api/health/readiness
                  scheme: HTTP
                  port: 3000
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 5
                successThreshold: 1
                timeoutSeconds: 1
              livenessProbe:
                httpGet:
                  path: /api/health/liveness
                  scheme: HTTP
                  port: 3000
                initialDelaySeconds: 60
                periodSeconds: 3
                failureThreshold: 2
                successThreshold: 1
                timeoutSeconds: 1
              image: ravenclaw
              name: ravenclaw
              securityContext:
                privileged: false
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              env: null
              resources: null
              limits:
                cpu: 200m
                memory: 400Mi
              requests:
                cpu: 100m
                memory: 200Mi
  - apiVersion: v1
    kind: Service
    spec:
      selector:
        project: ravenclaw
        provider: nodeshift
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          name: http
      type: ClusterIP
    metadata:
      name: ravenclaw
      namespace: demojam
      labels:
        project: ravenclaw
        version: 1.0.0
        provider: nodeshift
      annotations:
        nodeshift/git-branch: demojam
        nodeshift/git-commit: df797099435c086139688785420555b4a576770b
