spec:
  template:
    metadata:
      labels:
        app: reviews
        name: reviews
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: reviews
          env:
          - name: MONGO_CONNECTION_STRING
            valueFrom:
              configMapKeyRef:
                key: connection_string
                name: mongo-configuration
          - name: MONGO_DBNAME
            valueFrom:
              configMapKeyRef:
                key: db_name
                name: mongo-configuration
          ports:
          - containerPort: 8080
            protocol: TCP
            name: http
          readinessProbe:
            httpGet:
              path: /api/health/readiness
              port: 3000
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /api/health/liveness
              port: 3000
              scheme: HTTP
            failureThreshold: 2
            initialDelaySeconds: 60
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
