apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: cart
      namespace: node-store
      labels:
        project: cart
        version: 1.0.0
        provider: nodeshift
        app: cart
      annotations:
        nodeshift/git-branch: master
        nodeshift/git-commit: 02650b47143908d7f08d339e82678e41fbe8a53b
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        app: cart
        project: cart
        provider: nodeshift
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - cart
            from:
              kind: ImageStreamTag
              name: 'cart:latest'
      template:
        metadata:
          labels:
            project: cart
            version: 1.0.0
            provider: nodeshift
            app: cart
            name: cart
          annotations:
            sidecar.istio.io/inject: 'true'
            nodeshift/git-branch: master
            nodeshift/git-commit: 02650b47143908d7f08d339e82678e41fbe8a53b
        spec:
          containers:
            - readinessProbe:
                httpGet:
                  path: /api/health/readiness
                  scheme: HTTP
                  port: 3000
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 5
                successThreshold: 1
                timeoutSeconds: 1
              livenessProbe:
                httpGet:
                  path: /api/health/liveness
                  scheme: HTTP
                  port: 3000
                initialDelaySeconds: 60
                periodSeconds: 3
                failureThreshold: 2
                successThreshold: 1
                timeoutSeconds: 1
              image: cart
              name: cart
              securityContext:
                privileged: false
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              env:
                - name: MONGO_CONNECTION_STRING
                  valueFrom:
                    configMapKeyRef:
                      key: connection_string
                      name: mongo-configuration
                - name: MONGO_DBNAME
                  valueFrom:
                    configMapKeyRef:
                      key: db_name
                      name: mongo-configuration
              resources: null
              limits:
                cpu: 200m
                memory: 400Mi
              requests:
                cpu: 100m
                memory: 200Mi
  - apiVersion: v1
    kind: Service
    spec:
      selector:
        project: cart
        provider: nodeshift
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          name: http
      type: ClusterIP
    metadata:
      name: cart
      namespace: node-store
      labels:
        project: cart
        version: 1.0.0
        provider: nodeshift
      annotations:
        nodeshift/git-branch: master
        nodeshift/git-commit: 02650b47143908d7f08d339e82678e41fbe8a53b
